language: generic 
sudo: required 
services:
  - docker
before_install: 
  - docker build -t intizarahmad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true intizarahmad/docker-react npm test
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-338801737936"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_ACCESS_KEY