language: generic 
sudo: required 
services:
  - docker
before_install: 
  - docker build -t intizarahmad/docker-react -f Dockerfile.dev .
scripts:
  - docker run -e CI=true intizarahmad/docker-react npm run test -- --coverage
 